site_name: Proyecto Física Computacional
theme:
  name: material
  language: es
nav:
  - Inicio: index.md
  - Explicación del Problema: explication.md
  - Compilación: compilation.md
  - Resultados: results.md
  - Referencia: reference.md
  - Bibliografía: bibliography.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js