site_name: Proyecto Física Computacional
theme:
  name: material
  language: es
nav:
  - Inicio: index.md
  - Explicación del Problema: explication.md
  - Compilación: compilation.md
  - Resultados: results.md
  - Referencia: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js